ThaoPhuong/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThaoPhuong.Models;
using ThaoPhuong.Utils;

namespace ThaoPhuong.Controllers
{
    [FilterUrl]
    public class AdminController : Controller
    {
        THAOPHUONGEntities db = new THAOPHUONGEntities();
        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.data = SconfigController.LayDuLieuThongBaoKhachHang(db);
            return View();
        }

        public ActionResult CongNoKhachHang()
        {
            string query = @"SELECT * FROM
            (
	            SELECT ID, NAME, DIENTHOAI, DIACHI, 
	            (
		            SELECT SUM(COALESCE(TONGCONG, 0) - COALESCE(TIENTHANHTOAN, 0)) FROM TTHANHTOAN WHERE DKHACHHANGID = DKHACHHANG.ID
	            ) AS CONGNO
	            FROM DKHACHHANG
            )
            A
            WHERE A.CONGNO <> 0";
            DataTable dt = DbUtils.GetTable(db, query, null);
            return View(dt);
        }

        public ActionResult XoaDuLieu()
        {
            return View();
        }

        [HttpPost]
        public ActionResult XoaDuLieu(string password, string toDateStr)
        {
            string error = "";
            if (ModelState.IsValid)
            {
                if (toDateStr == null || toDateStr.Length == 0)
                {
                    error = "Ngày không hợp lệ";
                }
                else
                {
                    if (password.Length < 4)
                    {
                        error = "Ngày không hợp lệ";
                    }
                    else
                    {
                        password = password.Substring(0, password.Length - 4);
                        password = DbUtils.EncrytPass(password);
                        DKHACHHANG khRow = Session[Contants.USER_SESSION_NAME] as DKHACHHANG;
                        khRow = db.DKHACHHANGs.Where(x=>x.USERNAME.ToLower() == "admin" && x.PASSWORD == password).FirstOrDefault();
                        if (khRow == null)
                        {
                            error = "Mật khẩu xóa dữ liệu không hợp lệ";
                        }
                        else
                        {
                            try
                            {
                                DateTime date = DateTime.ParseExact(toDateStr, "MM/dd/yyyy", null);
                                SqlParameter param = new SqlParameter("@NGAY", System.Data.SqlDbType.Date);
                                param.Value = date;

                                //xóa ảnh + dữ liệu ảnh
                                List<DANH> lstAnhs = db.DANHs.SqlQuery("SELECT * FROM DANH WHERE EXISTS (SELECT * FROM TDONHANG WHERE TDONHANGID = TDONHANG.ID AND CAST(TIMECREATED AS DATE) <= @NGAY)", param).ToList();
                                //Xóa ảnh
                                foreach (DANH anh in lstAnhs)
                                {
                                    FileUpload.Delete(Server, anh.PATH);
                                }
                                //Xóa dữ liệu
                                db.DANHs.RemoveRange(lstAnhs);
                                db.SaveChanges();

                                //xóa chi tiết
                                param = new SqlParameter("@NGAY", System.Data.SqlDbType.Date);
                                param.Value = date;
                                string sql = "DELETE FROM TDONHANGCHITIET WHERE EXISTS (SELECT * FROM TDONHANG WHERE TDONHANGID = TDONHANG.ID AND CAST(TIMECREATED AS DATE) <= @NGAY)";
                                db.Database.ExecuteSqlCommand(sql, param);

                                //xóa đơn hàng
                                param = new SqlParameter("@NGAY", System.Data.SqlDbType.Date);
                                param.Value = date;
                                db.Database.ExecuteSqlCommand("DELETE FROM TDONHANG WHERE CAST(TIMECREATED AS DATE) <= @NGAY", param);
                            }
                            catch (Exception ex)
                            {
                                error = ex.Message;
                            }
                        }
                    }
                }
            }
            if (error.Length > 0)
            {
                ViewBag.error = error;
            }
            return View();
        }
    }
}

ThaoPhuong/Controllers/DQUAYController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThaoPhuong.Models;
using ThaoPhuong.Utils;

namespace ThaoPhuong.Controllers
{
    [FilterUrl]
    public class DQUAYController : Controller
    {
        private THAOPHUONGEntities db = new THAOPHUONGEntities();

        // GET: DQUAY
        public ActionResult Index()
        {
            return View(db.DQUAYs.OrderByDescending(x=>x.POSITION).ToList());
        }

        // GET: DQUAY/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DQUAY/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NAME,POSITION,GIAODICH")] DQUAY dQUAY)
        {
            if (ModelState.IsValid)
            {
                dQUAY.ID = Guid.NewGuid().ToString();
                db.DQUAYs.Add(dQUAY);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dQUAY);
        }

        // GET: DQUAY/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DQUAY dQUAY = db.DQUAYs.Find(id);
            if (dQUAY == null)
            {
                return HttpNotFound();
            }
            return View(dQUAY);
        }

        // POST: DQUAY/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NAME,POSITION,GIAODICH")] DQUAY dQUAY)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dQUAY).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dQUAY);
        }

        // GET: DQUAY/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DQUAY dQUAY = db.DQUAYs.Find(id);
            if (dQUAY == null)
            {
                return HttpNotFound();
            }
            return View(dQUAY);
        }

        // POST: DQUAY/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DQUAY dQUAY = db.DQUAYs.Find(id);
            db.DQUAYs.Remove(dQUAY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThaoPhuong/Controllers/DonGomController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThaoPhuong.Models;
using ThaoPhuong.Utils;

namespace ThaoPhuong.Controllers
{
    [FilterUrl]
    public class DonGomController : Controller
    {
        THAOPHUONGEntities db = new THAOPHUONGEntities();
        // GET: DonGom
        public ActionResult Index()
        {
            string fDateStr = null, tDateStr = null, fUpdateStr = null, tUpdateStr = null, DKHACHHANGID = null, DQUAYID = null, DTRANGTHAIID = null, sortName = null, sortDirection = null, giaoDich = null, loadIndex = null;
            GetParamFromUrl(Request.Params, ref fDateStr, ref tDateStr, ref fUpdateStr, ref tUpdateStr, ref DKHACHHANGID, ref DQUAYID, ref DTRANGTHAIID, ref sortName, ref sortDirection, ref giaoDich, ref loadIndex, false);

            giaoDich = giaoDich ?? "-1";
            //giao diện
            ViewBag.layout = Contants.LAYOUT_HOME;
            ViewBag.khachHangs = db.DKHACHHANGs.Where(x => x.ISADMIN != 30 && x.ISACTIVE > 0).ToList();
            ViewBag.quays = db.DQUAYs.ToList();
            ViewBag.trangthais = db.DTRANGTHAIs.OrderBy(x => x.ID).ToList();
            DKHACHHANG khRow = Session[Contants.USER_SESSION_NAME] as DKHACHHANG;
            ViewBag.isAdmin = false;
            if (SessionUtils.IsAdmin(Session))
            {
                ViewBag.isAdmin = true;
                ViewBag.layout = Contants.LAYOUT_ADMIN;
            }
            else
            {
                DKHACHHANGID = khRow.ID;
            }
            //Lọc ngày, lọc theo trạng thái, lọc khách hàng
            if (DTRANGTHAIID == null || DTRANGTHAIID.Length == 0) DTRANGTHAIID = "1";
            DateTime toDay = DateTime.Now.Date;
            DateTime fromDate = (fDateStr != null && fDateStr.Length > 0) ? DateTime.ParseExact(fDateStr, "MM/dd/yyyy", null) : toDay.AddMonths(-1);
            DateTime toDate = (tDateStr != null && tDateStr.Length > 0) ? DateTime.ParseExact(tDateStr, "MM/dd/yyyy", null) : toDay;
            DateTime fromUpdate = (fUpdateStr != null && fUpdateStr.Length > 0) ? DateTime.ParseExact(fUpdateStr, "MM/dd/yyyy", null) : toDay.AddMonths(-1);
            DateTime toUpdate = (tUpdateStr != null && tUpdateStr.Length > 0) ? DateTime.ParseExact(tUpdateStr, "MM/dd/yyyy", null) : toDay;
            ViewBag.fDateStr = fromDate.ToString("MM/dd/yyyy");
            ViewBag.tDateStr = toDate.ToString("MM/dd/yyyy");

            bool locNgayUpdate = (fUpdateStr != null && fUpdateStr.Length > 0) && (tUpdateStr != null && tUpdateStr.Length > 0);
            if (locNgayUpdate)
            {
                ViewBag.fUpdateStr = fromUpdate.ToString("MM/dd/yyyy");
                ViewBag.tUpdateStr = toUpdate.ToString("MM/dd/yyyy");
            }

            ViewBag.DKHACHHANGID = DKHACHHANGID;
            ViewBag.DQUAYID = DQUAYID;
            ViewBag.DTRANGTHAIID = DTRANGTHAIID;
            ViewBag.giaoDich = giaoDich;
            //Sắp xếp theo ngày, vị trí - Tăng giảm
            //Khách hàng thì mặc định ngày giảm
            ViewBag.sortName = sortName ?? "vitri";
            ViewBag.sortDirection = sortDirection ?? "tang";
            if (!ViewBag.isAdmin)
            {
                ViewBag.sortName = sortName ?? "ngay";
                ViewBag.sortDirection = sortDirection ?? "giam";
            }

            List<TDONHANG> lst = new List<TDONHANG>();
            IQueryable<TDONHANG> iQueryable = db.TDONHANGs.Where(x => x.LOAI == 0);
            iQueryable = iQueryable.Where(x => DbFunctions.TruncateTime(x.TIMECREATED ?? toDay).Value >= fromDate && DbFunctions.TruncateTime(x.TIMECREATED ?? toDay).Value <= toDate);
            iQueryable = iQueryable.Where(x => x.DKHACHHANGID == DKHACHHANGID || DKHACHHANGID == null || DKHACHHANGID.Length == 0);
            iQueryable = iQueryable.Where(x => x.DTRANGTHAIID == DTRANGTHAIID || DTRANGTHAIID == "TatCa");
            iQueryable = iQueryable.Where(x => x.DQUAYID == DQUAYID || DQUAYID == null || DQUAYID.Length == 0);

            if (locNgayUpdate)
            {
                DateTime tmp = toUpdate.AddMonths(1);
                iQueryable = iQueryable.Where(x => DbFunctions.TruncateTime(x.TIMEUPDATED ?? tmp).Value >= fromUpdate && DbFunctions.TruncateTime(x.TIMEUPDATED ?? tmp).Value <= toUpdate);
            }

            if (giaoDich != "-1")
            {
                iQueryable = iQueryable.Where(x => ((x.DQUAYID != null || x.DQUAYID.Length > 0) && x.DQUAY.GIAODICH.ToString() == giaoDich)
                || (giaoDich == "2" && x.DQUAY == null));
            }
            IOrderedQueryable<TDONHANG> iOrderedQueryable;
            if (ViewBag.sortDirection == "tang")
            {
                if (ViewBag.sortName == "ngay") iOrderedQueryable = iQueryable.OrderBy(x => x.TIMECREATED);
                else iOrderedQueryable = iQueryable.OrderBy(x => x.DQUAY.POSITION ?? 999999999);
            }
            else
            {
                if (ViewBag.sortName == "ngay") iOrderedQueryable = iQueryable.OrderByDescending(x => x.TIMECREATED);
                else iOrderedQueryable = iQueryable.OrderByDescending(x => x.DQUAY.POSITION ?? 999999999);
            }
            lst = iOrderedQueryable.ToList();

            return View(lst);
        }

        [HttpGet]
        public ActionResult AddOrUpdate(string id, int? loadIndex)
        {
            bool isAdmin = SessionUtils.IsAdmin(Session);
            ViewBag.layout = Contants.LAYOUT_HOME;
            if (isAdmin)
            {
                ViewBag.layout = Contants.LAYOUT_ADMIN;
            }
            ViewBag.quays = db.DQUAYs.OrderBy(x => x.POSITION).ToList();
            ViewBag.trangthais = db.DTRANGTHAIs.OrderBy(x => x.ID).ToList();
            ViewBag.isAdmin = isAdmin;

            TDONHANG dhRow = null;
            if (id != null && id.Length > 0)
            {
                dhRow = db.TDONHANGs.Where(x => x.ID == id).FirstOrDefault();
                if (dhRow == null) return View("~/Views/Shared/Error.cshtml");

                ViewBag.imgs = GetDicAnhs(db, dhRow);
            }
            else dhRow = new TDONHANG();
            if (dhRow.NAME == null || dhRow.NAME.Length == 0)
            {
                dhRow.NAME = "Tự động";
                dhRow.TONGCONG = 10000;
            }

            ViewBag.loadIndex = loadIndex;
            return View(dhRow);
        }

        public static void GetParamFromUrl(NameValueCollection @params, ref string fDateStr, ref string tDateStr, ref string fUpdateStr, ref string tUpdateStr,
            ref string DKHACHHANGID, ref string DQUAYID, ref string DTRANGTHAIID, ref string sortName, ref string sortDirection, ref string giaoDich,
            ref string loadIndex, bool endp)
        {
            List<string> lstKeys = new List<string>(@params.AllKeys);
            if (lstKeys.Contains((endp ? "p" : "") + "fDateStr")) fDateStr = @params[(endp ? "p" : "") + "fDateStr"];
            if (lstKeys.Contains((endp ? "p" : "") + "tDateStr")) tDateStr = @params[(endp ? "p" : "") + "tDateStr"];
            if (lstKeys.Contains((endp ? "p" : "") + "fUpdateStr")) fUpdateStr = @params[(endp ? "p" : "") + "fUpdateStr"];
            if (lstKeys.Contains((endp ? "p" : "") + "tUpdateStr")) tUpdateStr = @params[(endp ? "p" : "") + "tUpdateStr"];
            if (lstKeys.Contains((endp ? "p" : "") + "DKHACHHANGID")) DKHACHHANGID = @params[(endp ? "p" : "") + "DKHACHHANGID"];
            if (lstKeys.Contains((endp ? "p" : "") + "DQUAYID")) DQUAYID = @params[(endp ? "p" : "") + "DQUAYID"];
            if (lstKeys.Contains((endp ? "p" : "") + "DTRANGTHAIID")) DTRANGTHAIID = @params[(endp ? "p" : "") + "DTRANGTHAIID"];
            if (lstKeys.Contains((endp ? "p" : "") + "sortName")) sortName = @params[(endp ? "p" : "") + "sortName"];
            if (lstKeys.Contains((endp ? "p" : "") + "sortDirection")) sortDirection = @params[(endp ? "p" : "") + "sortDirection"];
            if (lstKeys.Contains((endp ? "p" : "") + "giaoDich")) giaoDich = @params[(endp ? "p" : "") + "giaoDich"];
            if (lstKeys.Contains("loadIndex")) loadIndex = @params["loadIndex"];
        }

        public static Dictionary<string, string> GetDicAnhs(THAOPHUONGEntities db, TDONHANG dhRow)
        {
            Dictionary<string, string> dic = new Dictionary<string, string>();
            List<DANH> lstAnhs = db.DANHs.Where(x => x.TDONHANGID == dhRow.ID).ToList();
            foreach (DANH anh in lstAnhs)
            {
                dic.Add(anh.ID, "/Images/Upload/" + anh.PATH);
            }
            return dic;
        }

        [HttpPost]
        public ActionResult AddOrUpdate(TDONHANG item)
        {
            string fDateStr = null, tDateStr = null, fUpdateStr = null, tUpdateStr = null, DKHACHHANGID = null, DQUAYID = null, DTRANGTHAIID = null, sortName = null, sortDirection = null, giaoDich = null, loadIndex = null;
            GetParamFromUrl(Request.Params, ref fDateStr, ref tDateStr, ref fUpdateStr, ref tUpdateStr, ref DKHACHHANGID, ref DQUAYID, ref DTRANGTHAIID, ref sortName, ref sortDirection, ref giaoDich, ref loadIndex, true);

            bool isNewItem = false;
            TDONHANG dhRow = new TDONHANG();
            try
            {
                ViewBag.quays = db.DQUAYs.OrderBy(x => x.POSITION).ToList();
                ViewBag.trangthais = db.DTRANGTHAIs.OrderBy(x => x.ID).ToList();
                ViewBag.imgs = GetDicAnhs(db, dhRow);
                if (ModelState.IsValid)
                {
                    //kiểm tra xem up ảnh hay chưa
                    List<HttpPostedFileBase> files = new List<HttpPostedFileBase>();
                    files.AddRange(Request.Files.GetMultiple("images[]"));
                    string[] preloaded = Request.Params.GetValues("preloaded[]");
                    bool hasImg = false;
                    foreach (HttpPostedFileBase file in files)

ThaoPhuong/Views/Shared/_Admin.cshtml
@{
    string id = "";
    ThaoPhuong.Models.DKHACHHANG khRow = Session[ThaoPhuong.Utils.Contants.USER_SESSION_NAME] as ThaoPhuong.Models.DKHACHHANG;
    if (khRow != null && khRow.ID.Length > 0)
    {
        id = khRow.ID;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Home/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Home/image-uploader.css" rel="stylesheet" />
    <link href="~/Content/Home/Site.css" rel="stylesheet" />
    <link href="~/Content/select2.css" rel="stylesheet" />
    <link href="~/Content/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        @Html.ActionLink("Trang chủ", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Thông tin chung
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Thông báo khách hàng", "ThongBaoKhachHang", "SCONFIG")</li>
                        <li class="dropdown-item">@Html.ActionLink("Công nợ khách hàng", "CongNoKhachHang", "Admin")</li>
                        <li class="dropdown-item">@Html.ActionLink("Xóa dữ liệu", "XoaDuLieu", "Admin")</li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Danh mục
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Danh sách trạng thái", "Index", "DTRANGTHAI")</li>
                        <li class="dropdown-item">@Html.ActionLink("Danh sách quầy", "Index", "DQUAY")</li>
                        <li class="dropdown-item">@Html.ActionLink("Danh sách khách hàng", "Index", "DKHACHHANG")</li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hoạt động
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="dropdown-item">@Html.ActionLink("Quản lý đơn gom", "Index", "DonGom")</li>
                        <li class="dropdown-item">@Html.ActionLink("Quản lý đơn nhặt", "Index", "DonNhat")</li>
                        <li class="dropdown-item">@Html.ActionLink("Thêm mới thanh toán", "AddOrUpdate", "ThanhToan")</li>
                        <li class="dropdown-item">@Html.ActionLink("Quản lý thanh toán", "Index", "ThanhToan")</li>
                    </ul>
                </li>

                @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Phiếu thanh toán
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li class="dropdown-item">@Html.ActionLink("Thêm mới", "AddOrUpdate", "ThanhToan")</li>
                <li class="dropdown-item">@Html.ActionLink("Danh sách phiếu thanh toán", "Index", "ThanhToan")</li>
            </ul>
        </li>*@

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Thông tin cá nhân
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <li class="dropdown-item">@Html.ActionLink("Thông tin", "Index", "Profile", new { id = id }, null)</li>
                        <li class="dropdown-item">@Html.ActionLink("Đổi mật khẩu", "EditPassword", "Profile")</li>
                        <li class="dropdown-item">@Html.ActionLink("Đăng xuất", "Logout", "Profile")</li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/select2.js"></script>
    <script src="~/Scripts/daterangepicker.js"></script>
    <script src="~/Scripts/utils.js"></script>
    @*<script src="~/Scripts/image-uploader.js"></script>*@
    <script>
        $(document).ready(function () {
            $('.select2').select2();
            $('#startDate').datepicker({
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'fontawesome'
            });
            $('#endDate').datepicker({
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'fontawesome'
            });
            $('#startUpdate').datepicker({
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'fontawesome'
            });
            $('#endUpdate').datepicker({
                uiLibrary: 'bootstrap4',
                iconsLibrary: 'fontawesome'
            });
        });
    </script>
</body>
</html>

ThaoPhuong/Views/Shared/_LoginRes.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    @Styles.Render("~/Content/Admin/vendor/fontawesome-free/css/all.min.css")
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    @Styles.Render("~/Content/Admin/css/sb-admin-2.css")
</head>
<body class="bg-gradient-primary">
    @RenderBody()
    @Scripts.Render("~/Content/Admin/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/Content/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/Content/Admin/vendor/jquery-easing/jquery.easing.min.js")
    @Scripts.Render("~/Content/Admin/js/sb-admin-2.min.js")
</body>
</html>